kafka:
  clusters:
    -
      name: local
      bootstrapServers: kafka1:29091,kafka2:29092,kafka3:29093
      schemaRegistry: http://schema-registry:8081
      # schemaRegistryAuth:
      #   username: username
      #   password: password
#     schemaNameTemplate: "%s-value"
      metrics:
        port: 9997
        type: JMX